/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import calses.Gato;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashley
 */
public class FrmTablero extends javax.swing.JFrame {

    private Creditos creditos;                      // declarando una instancia de el  formulario Creditos
    private FrmIntro frmIntro;                      // declarando una instancia de el  formulario FrmIntro
    private Gato gato;                              // declarando una instancia de la clase Gato
    private JLabel[] tablero;                       // Arreglo de etiquetas para 
    private boolean[] volteadas = new boolean[9];   // Arreglo de booleanos para las posiciones 
    private boolean banInicio;

    /**
     * Creates new form FrmTablero
     */
    public FrmTablero() {
        initComponents();
        gato = new Gato();
        tablero = new JLabel[9];
        tablero[0] = lblImagen1;
        tablero[1] = lblImagen2;
        tablero[2] = lblImagen3;
        tablero[3] = lblImagen4;
        tablero[4] = lblImagen5;
        tablero[5] = lblImagen6;
        tablero[6] = lblImagen7;
        tablero[7] = lblImagen8;
        tablero[8] = lblImagen9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen5 = new javax.swing.JLabel();
        lblImagen6 = new javax.swing.JLabel();
        lblImagen7 = new javax.swing.JLabel();
        lblImagen8 = new javax.swing.JLabel();
        lblImagen9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTirador = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego del Gato");

        lblImagen1.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen1MouseClicked(evt);
            }
        });

        lblImagen2.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen2MouseClicked(evt);
            }
        });

        lblImagen3.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen3MouseClicked(evt);
            }
        });

        lblImagen4.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen4MouseClicked(evt);
            }
        });

        lblImagen5.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen5MouseClicked(evt);
            }
        });

        lblImagen6.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen6MouseClicked(evt);
            }
        });

        lblImagen7.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen7MouseClicked(evt);
            }
        });

        lblImagen8.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen8MouseClicked(evt);
            }
        });

        lblImagen9.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/fondo.jpg"))); // NOI18N
        lblImagen9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen9MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tirador:");

        lblTirador.setBackground(new java.awt.Color(255, 255, 255));
        lblTirador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTirador.setForeground(new java.awt.Color(255, 0, 0));

        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegistrar1.setText("Creditos");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRegistrar1)
                            .addGap(115, 115, 115)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTirador, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTirador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistrar))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * metodo para dar funcionalidad al boton Registrar
     *
     * @param evt
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        frmIntro = new FrmIntro(gato);
        frmIntro.setVisible(true);      //Hacer visible el FrmInicio
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * Metodo para hacer que en el lblTirador se muestre el jugador que esta
     * realizando el tiero
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblTirador.setText(gato.getJugador1());
        banInicio = false;
    }//GEN-LAST:event_formWindowActivated

    /**
     * Metodos para cuando seleccionamos una casilla
     *
     * @param evt
     */
    private void lblImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseClicked
        // TODO add your handling code here:
        tirar(0);
    }//GEN-LAST:event_lblImagen1MouseClicked

    private void lblImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseClicked
        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen2MouseClicked

    private void lblImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseClicked
        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen3MouseClicked

    private void lblImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseClicked
        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen4MouseClicked

    private void lblImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseClicked
        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen5MouseClicked

    private void lblImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseClicked
        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen6MouseClicked

    private void lblImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseClicked
        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen7MouseClicked

    private void lblImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseClicked
        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen8MouseClicked

    private void lblImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseClicked
        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen9MouseClicked

    /**
     * Metodo para dar funcion a el boton Nuevo el cual reinicia el tablero y
     * borra los datos de el jueg anterior
     *
     * @param evt
     */
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 9; i++) {
            volteadas[i] = false;
            tablero[i].setIcon(
                    new ImageIcon(getClass().getResource("/gato/fondo.jpg")));
        }
        gato.reiniciar();
        banInicio = true;
    }//GEN-LAST:event_btnNuevoActionPerformed
    /**
     * Metodo que muestra el formulario Creditos
     *
     * @param evt
     */
    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        creditos = new Creditos();
        creditos.setVisible(true);      // hece visible los Creditos
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    /**
     * Motodo para poder darle funcionalidad al boton Salir
     *
     * @param evt
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Metodo para poder realizar un tiro y registrar los datos
     *
     * @param pos
     */
    private void tirar(int pos) {
        if (banInicio) {
            if (volteadas[pos] == false && gato.ganador() == 0 && gato
                    .getTiros() < 9) {
                volteadas[pos] = true;
                gato.setTiro(pos);      //<------
                // en caso de que el jugador uno sea el
                //que tira y haya escojido jugar con la X
                if (gato.isTurnoJ1()) {
                    if (gato.getTiroJ1() == 1) {                            // Equis
                        tablero[pos].setIcon(new ImageIcon(
                                getClass().getResource("/gato/X.jpg")));
                        // en caso de que haya escogido la O para jugar
                    } else {
                        tablero[pos].setIcon(new ImageIcon(
                                getClass().getResource("/gato/O.jpg")));
                    }
                    // en caso de que el jugador dos dea el que
                    //tira y haya elegido jugar con la X    
                } else {
                    if (gato.getTiroJ2() == 1) {                            // Equis
                        tablero[pos].setIcon(new ImageIcon(
                                getClass().getResource("/gato/X.jpg")));
                        // en caso de que el jugador dos haya escogido jugar con O
                    } else {
                        tablero[pos].setIcon(new ImageIcon(
                                getClass().getResource("/gato/O.jpg")));
                    }
                }
                // cuando alguno de los dos jugadores haya ganado
                if (gato.ganador() != 0) {
                    JOptionPane.showMessageDialog(this, "Ganó "
                            + lblTirador.getText() + "!!");
                    // Si se declara empate
                } else if (gato.esEmpate()) {
                    JOptionPane.showMessageDialog(this, "Es empate!!");
                    // Si ninguno a ganado y existen casillas libres aun 
                } else {
                    gato.cambiarTurno();
                    if (gato.isTurnoJ1()) {
                        lblTirador.setText(gato.getJugador1());
                    } else {
                        lblTirador.setText(gato.getJugador2());
                    }
                }
            }
            /**
             * El switch nos servira para poder poner que se mostrara o que se
             * hara cuando alguno de los jugadores haya ganado o se haya
             * declarado empate,
             */
            switch (gato.ganador()) {
                case 0:
                    if (gato.esEmpate()) {
                        JOptionPane.showMessageDialog(this, "Es empate!!");
                    }
                    break;
                case 1:     //fila #1
                    // en este caso se mostraran las imagenes con una linea horizontal

                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }

                    }
                    break;
                case 2:     //fila #2
                    // en este caso se mostraran las imagenes con una linea horizontal
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }

                    }
                    break;
                case 3:     //fila #3
                    // en este caso se mostraran las imagenes con una linea horizontal
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X2.jpg")));
                        } else {
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O2.jpg")));
                        }

                    }
                    break;

                case 4:     //columna #1
                    // en este caso se mostraran las imagenes con una linea vertical
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }

                    }
                    break;

                case 5:     //columna #2
                    // en este caso se mostraran las imagenes con una linea vertical
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }

                    }
                    break;

                case 6:     //columna #3
                    // en este caso se mostraran las imagenes con una linea vertical
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X1.jpg")));
                        } else {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O1.jpg")));
                        }

                    }
                    break;

                case 7:     //diagonal #1
                    // en este caso se mostraran las imagenes con una linea en diagonal
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X3.jpg")));
                        } else {
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O3.jpg")));
                        }

                    }
                    break;

                case 8:     //diagonal #2
                    // en este caso se mostraran las imagenes con una linea en diagonal
                    if (gato.isTurnoJ1()) {
                        if (gato.getTiroJ1() == 1) {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                        } else {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                        }
                    } else {

                        if (gato.getTiroJ1() == 2) {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/X4.jpg")));
                        } else {
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/gato/O4.jpg")));
                        }

                    }
                    break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblImagen8;
    private javax.swing.JLabel lblImagen9;
    private javax.swing.JLabel lblTirador;
    // End of variables declaration//GEN-END:variables
}// Fin clase
